
development:
  adapter: postgresql
  encoding: unicode
  database: thegoat_development

test:
  adapter: postgresql
  encoding: unicode
  database: thegoat_test

staging:
  adapter: postgresql
  encoding: unicode
  database: thegoat_staging

production:
  adapter: postgresql
  encoding: unicode
  database: thegoat_production
